### ISSUE TITLE
Difference between your FF-database and the original one

### ISSUE THREAD

**Issue by itsnickchiu** [CVI-SZU/StyleGene#3]
Hi, thanks for your excellent work!

It seems that your images of FF-database is somewhat different with the original dataset accessed from CityU. 
For example, I found that the original ones are cropped only on facial features (i.e., without ears, hair, and background), but yours have those components that the original ones do not have.

Therefore, I wonder that if you crawled the images via ChildPredictor and cropped with different size or you have other preprocessing pipelines.

**Comment by wmpscc** [comment]
Thank you for your attention. 

I contacted the author of ChildPredictor and obtained the raw image data. I reprocessed some data following the alignment method of the FFHQ dataset.

**Comment by itsnickchiu** [comment]
Thanks for your immediate response.

Do you mean you obtain the raw family images (i.e., a bunch of people in a single image) in the original FF-database from the author, and then crop and align via the method of the FFHQ dataset?

If that is the case, could you provide the images you've processed? If you could not and it's totally fine.

**Comment by wmpscc** [comment]
Yes, I got the raw family images from the author. I cropped and used a facial recognition model to assist in re-labeling their family relationships. I haven't annotated the entire dataset, so I can't provide it, my apologies.
